#!/usr/bin/env python3
"""Embed magmascript/lang/ into the browser playground.

The playground runs the real interpreter under Pyodide, which means the Python
sources have to be written into Pyodide's filesystem before anything can be
imported. They are embedded directly in app.js so the playground stays a
self-contained set of static files.

Keeping that embedding by hand does not work. It was already one major version
behind — app.js shipped a pre-3.0 snapshot with no Asthenosphere at all, so the
playground silently ran v2.x semantics — and a hand-maintained parallel list of
filenames is a second thing to forget. Run this instead:

    python scripts/embed-playground.py

Sources are written as JSON strings rather than JS template literals. JSON is
valid JavaScript and json.dumps escaping is total, so backslashes, backticks and
${ sequences in Python source cannot break the generated file. Template literals
required hand-managing exactly those, which is what the earlier
"Fix lang file escaping for JS template literals" commit was about.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
LANG_DIR = REPO / "magmascript" / "lang"
APP_JS = REPO / "playground" / "app.js"

BEGIN = "// BEGIN GENERATED LANG FILES"
END = "// END GENERATED LANG FILES"

# Needs Pygments, which is not available in Pyodide and which the playground
# does not use — it has its own editor highlighting.
SKIP_NAMES = {"pygments_mgs.py"}


def collect() -> dict[str, str]:
    """Every lang module, keyed by its path relative to magmascript/lang/."""
    files: dict[str, str] = {}
    for path in sorted(LANG_DIR.rglob("*.py")):
        if "__pycache__" in path.parts or path.name in SKIP_NAMES:
            continue
        files[path.relative_to(LANG_DIR).as_posix()] = path.read_text(encoding="utf-8")
    return files


def render(files: dict[str, str]) -> str:
    lines = [
        BEGIN,
        "// Generated by scripts/embed-playground.py — do not edit by hand.",
        f"// {len(files)} modules from magmascript/lang/",
        "const LANG_FILE_CONTENTS = {",
    ]
    for name, source in files.items():
        lines.append(f"  {json.dumps(name)}: {json.dumps(source)},")
    lines.append("};")
    lines.append(END)
    return "\n".join(lines)


def main() -> int:
    if not APP_JS.exists():
        print(f"error: {APP_JS} not found", file=sys.stderr)
        return 1

    files = collect()
    if not files:
        print("error: no lang modules found", file=sys.stderr)
        return 1

    app = APP_JS.read_text(encoding="utf-8")
    if BEGIN not in app or END not in app:
        print(
            f"error: markers not found in {APP_JS.name}.\n"
            f"       Wrap the LANG_FILE_CONTENTS block in:\n"
            f"         {BEGIN}\n         ...\n         {END}",
            file=sys.stderr,
        )
        return 1

    head, _, rest = app.partition(BEGIN)
    _, _, tail = rest.partition(END)
    updated = head + render(files) + tail

    if updated == app:
        print(f"unchanged — {len(files)} modules already embedded")
        return 0

    APP_JS.write_text(updated, encoding="utf-8", newline="\n")
    total = sum(len(s) for s in files.values())
    print(f"embedded {len(files)} modules ({total:,} chars) into {APP_JS.name}")
    for name in files:
        print(f"  {name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
